<?php

namespace AffectationBundle\Repository;

/**
 * AffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAffectation($remarque)
    {
        $query = $this->createQueryBuilder('a');
        $query->where("a.remarque like :remarque")->setParameter('remarque', '%'.$remarque.'%');

        return $query->getQuery()->getResult();
    }
}
