<?php

namespace AffectationBundle\Repository;

/**
 * ArgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArgentRepository extends \Doctrine\ORM\EntityRepository
{
}
