<?php

namespace AffectationBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDemande($remarque)
    {
        $query = $this->createQueryBuilder('d');
        $query->where("d.remarque like :remarque")->setParameter('remarque', '%'.$remarque.'%');

        return $query->getQuery()->getResult();
    }
}
